// 
//  AUTOGENERATED FILE:   do not edit
//
//  Generated by:         alex on alex-laptop, 2016-11-23 12:44:55 -0500
//  From Template/Script: data_templates/DataClassTemplate.cpp
 
/*
  CTA RIGHTS

  This document contains information proprietary to General Dynamics
  Robotic Systems and is not to be reproduced, transmitted, transferred,
  or otherwise used without the express written consent of General
  Dynamics Robotic Systems except as described below.

  GOVERNMENT PURPOSE RIGHTS

  Contract No.:        W911NF-10-2-0016, Articles of Collaboration,
                       Article 5, Intellectual Property
  Contractor Name:     General Dynamics Robotic Systems, Inc. (GDRS)
  Contractor Address:  1231 Tech Court, Westminster, MD  21157

  Expiration Date - None

  Technical data and computer software first created by Member(s) in
  performance of the Agreement will be disclosed to the Government.
  General Dynamics Robotic Systems retains the entire right, title, and
  interest throughout the world to each subject invention subject to the
  provisions of this clause and 37 CFR Part 401, 32 CFR 32.36, and
  34 CFR 34.25. The Government shall have the right to obtain, reproduce,
  publish or otherwise use the work for Government purposes.

  NON-EXCLUSIVE LICENSE TO CONSORTIUM PARTICIPANTS
  Consortium Members and subawardees are defined as 'Participants'
  Under Article 5.3, Participants are granted a nonexclusive, royalty-
  free, non-sublicenseable, non-assignable, license to Consortium
  Intellectual Property for the limited purpose of performing tasks under
  The Cooperative Agreement, for Government purposes only, and to make and
  have the same made solely for such use.

*/

#include <math.h> // to allow use of common constants...
#include <common/Error.h>
#include "std_msgs/HeaderTest.h"

#include <common/JsonIo.h> // include here so container types are included by the class header 

using namespace std;

const unsigned int std_msgs::HeaderTest::ID;
const unsigned int std_msgs::HeaderTest::DATA_VERSION;
const std::string std_msgs::HeaderTest::DATA_TYPE_NAME = "HeaderTest";
const std::string std_msgs::HeaderTest::DATA_TYPE_FULL_NAME = "std_msgs::HeaderTest";
const std::string std_msgs::HeaderTest::VERSION_MD5 = "bf966b0769097e322bc8dc3af8b05877";
/* xml source for this class */
const std::string std_msgs::HeaderTest::XML_SOURCE = "<class name=\"HeaderTest\" comment=\"testing of header serialization\" publicDataMembers=\"true\" ros=\"true\" generateNML=\"new\" rosDesc=\"header serialization test\" sourceIDL=\"ROS\" id=\"2068109263\">\
  <field name=\"header\" type=\"std_msgs::Header\" comment=\"ros header\"/>\
  <field name=\"header2\" type=\"std_msgs::Header\" comment=\"ros header\"/>\
</class>";

std_msgs::HeaderTest::HeaderTest() : header(), header2()
{  
};

std_msgs::HeaderTest::HeaderTest(const std_msgs::HeaderTest & inobj) : header(inobj.header), header2(inobj.header2)
{
};

std_msgs::HeaderTest::~HeaderTest()
{
};

std_msgs::HeaderTest * std_msgs::HeaderTest::New()
{ 
    return new HeaderTest();
};

bool std_msgs::HeaderTest::dataTypeFlat() 
{  
    return std_msgs::Header::dataTypeFlat();

};

std_msgs::HeaderTest & std_msgs::HeaderTest::operator=(const std_msgs::HeaderTest & inobj)
{
    if (this != &inobj)
    {

        // if datatype is flat, optimize with memcpy (complier level optimiation)
              /*  if (dataTypeFlat() == true)
                  REMOVED invalid when assigning from a parent type as this is the pointer to the derived type, thus std_msgs::HeaderTest is copied to the wrong location

        {
            memcpy(this,&inobj,sizeof(std_msgs::HeaderTest));
        }
        else */ 
        {

            header = inobj.header;
            header2 = inobj.header2;
        }
    }

    return *this;
}

bool std_msgs::HeaderTest::operator==(const std_msgs::HeaderTest & inobj) const
{
    bool ret = true;

    if (this != &inobj)
    { 
        ret = ret 
             && (header == inobj.header)
             && (header2 == inobj.header2);
    }

    return ret;
}

bool std_msgs::HeaderTest::operator!=(const std_msgs::HeaderTest & inobj) const
{
    bool ret = false;

    if (this != &inobj)
    {
        ret = !operator==(inobj);
    }

    return ret;
}

bool std_msgs::HeaderTest::operator<(const std_msgs::HeaderTest & inobj) const
{
    bool ret = false;

    if (this == &inobj)
    {
        ret = false;
    }
    else
    {  
        // comparison algorithm based on std::lexicographical_compare algorithm

        if (header < inobj.header) return true;
        if (inobj.header <  header) return false; 
        if (header2 < inobj.header2) return true;
        if (inobj.header2 <  header2) return false; ;
    }

    return ret;
}

bool std_msgs::HeaderTest::operator>(const std_msgs::HeaderTest & inobj) const
{
    bool ret = false;

    if (this == &inobj)
    {
        ret = false;
    }
    else
    {
        // comparison algorithm based on std::lexicographical_compare algorithm

        if (header > inobj.header) return true;
        if (inobj.header >  header) return false; 
        if (header2 > inobj.header2) return true;
        if (inobj.header2 >  header2) return false; ;
    }

    return ret;
}

template <> void rframe::json_io::encode(std::stringstream & sstr, const char * name, const std_msgs::HeaderTest & t, std::string & indent, bool lastItem)
{
    if ((name) && (*name != '\0')) rframe::json_io::encodeObjectStart(sstr,name,indent);

    rframe::json_io::encode(sstr,"header",t.header,indent,false);
    rframe::json_io::encode(sstr,"header2",t.header2,indent,true);

    if ((name) && (*name != '\0')) rframe::json_io::encodeObjectEnd(sstr,indent,lastItem);
}

std::string std_msgs::HeaderTest::toStr(bool pretty) const
{

    stringstream sstr;
    string indent = (pretty == true) ? "\n" : "";

    rframe::json_io::encodeObjectStartMain(sstr,indent);
    rframe::json_io::encode(sstr,"",*this,indent,true);
    rframe::json_io::encodeObjectEnd(sstr,indent,true); // false so as to  not add , at end of string

    return sstr.str();

};

std::basic_ostream<char>& operator<<(std::basic_ostream<char> &s, const std_msgs::HeaderTest & value)
{
    return s << value.toStr(false);
}

