// 
//  AUTOGENERATED FILE:   do not edit
//
//  Generated by:         alex on alex-laptop, 2016-11-23 12:44:51 -0500
//  From Template/Script: data_templates/DataClassTemplate.cpp
 
/*
  CTA RIGHTS

  This document contains information proprietary to General Dynamics
  Robotic Systems and is not to be reproduced, transmitted, transferred,
  or otherwise used without the express written consent of General
  Dynamics Robotic Systems except as described below.

  GOVERNMENT PURPOSE RIGHTS

  Contract No.:        W911NF-10-2-0016, Articles of Collaboration,
                       Article 5, Intellectual Property
  Contractor Name:     General Dynamics Robotic Systems, Inc. (GDRS)
  Contractor Address:  1231 Tech Court, Westminster, MD  21157

  Expiration Date - None

  Technical data and computer software first created by Member(s) in
  performance of the Agreement will be disclosed to the Government.
  General Dynamics Robotic Systems retains the entire right, title, and
  interest throughout the world to each subject invention subject to the
  provisions of this clause and 37 CFR Part 401, 32 CFR 32.36, and
  34 CFR 34.25. The Government shall have the right to obtain, reproduce,
  publish or otherwise use the work for Government purposes.

  NON-EXCLUSIVE LICENSE TO CONSORTIUM PARTICIPANTS
  Consortium Members and subawardees are defined as 'Participants'
  Under Article 5.3, Participants are granted a nonexclusive, royalty-
  free, non-sublicenseable, non-assignable, license to Consortium
  Intellectual Property for the limited purpose of performing tasks under
  The Cooperative Agreement, for Government purposes only, and to make and
  have the same made solely for such use.

*/

#include <math.h> // to allow use of common constants...
#include <common/Error.h>
#include "nav_msgs/GetMapGoal.h"

#include <common/JsonIo.h> // include here so container types are included by the class header 

using namespace std;

const unsigned int nav_msgs::GetMapGoal::ID;
const unsigned int nav_msgs::GetMapGoal::DATA_VERSION;
const std::string nav_msgs::GetMapGoal::DATA_TYPE_NAME = "GetMapGoal";
const std::string nav_msgs::GetMapGoal::DATA_TYPE_FULL_NAME = "nav_msgs::GetMapGoal";
const std::string nav_msgs::GetMapGoal::VERSION_MD5 = "790b61c662175e1b51d14f8724391020";
/* xml source for this class */
const std::string nav_msgs::GetMapGoal::XML_SOURCE = "<class name=\"GetMapGoal\" publicDataMembers=\"true\" sourceIDL=\"ROS\" ros=\"true\" rosMD5=\"d41d8cd98f00b204e9800998ecf8427e\" rosDesc=\"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\\n# Get the map as a nav_msgs/OccupancyGrid\\n\" comment=\"\" id=\"1589304791\">\
</class>";

nav_msgs::GetMapGoal::GetMapGoal() 
{  
};

nav_msgs::GetMapGoal::GetMapGoal(const nav_msgs::GetMapGoal & inobj) 
{
};

nav_msgs::GetMapGoal::~GetMapGoal()
{
};

nav_msgs::GetMapGoal * nav_msgs::GetMapGoal::New()
{ 
    return new GetMapGoal();
};

bool nav_msgs::GetMapGoal::dataTypeFlat() 
{  
    return true;
};

nav_msgs::GetMapGoal & nav_msgs::GetMapGoal::operator=(const nav_msgs::GetMapGoal & inobj)
{
    if (this != &inobj)
    {

        // if datatype is flat, optimize with memcpy (complier level optimiation)
              /*  if (dataTypeFlat() == true)
                  REMOVED invalid when assigning from a parent type as this is the pointer to the derived type, thus nav_msgs::GetMapGoal is copied to the wrong location

        {
            memcpy(this,&inobj,sizeof(nav_msgs::GetMapGoal));
        }
        else */ 
        {

        }
    }

    return *this;
}

bool nav_msgs::GetMapGoal::operator==(const nav_msgs::GetMapGoal & inobj) const
{
    bool ret = true;

    if (this != &inobj)
    { 
    }

    return ret;
}

bool nav_msgs::GetMapGoal::operator!=(const nav_msgs::GetMapGoal & inobj) const
{
    bool ret = false;

    if (this != &inobj)
    {
        ret = !operator==(inobj);
    }

    return ret;
}

bool nav_msgs::GetMapGoal::operator<(const nav_msgs::GetMapGoal & inobj) const
{
    bool ret = false;

    if (this == &inobj)
    {
        ret = false;
    }
    else
    {  
        // comparison algorithm based on std::lexicographical_compare algorithm
        ;
    }

    return ret;
}

bool nav_msgs::GetMapGoal::operator>(const nav_msgs::GetMapGoal & inobj) const
{
    bool ret = false;

    if (this == &inobj)
    {
        ret = false;
    }
    else
    {
        // comparison algorithm based on std::lexicographical_compare algorithm
        ;
    }

    return ret;
}

template <> void rframe::json_io::encode(std::stringstream & sstr, const char * name, const nav_msgs::GetMapGoal & t, std::string & indent, bool lastItem)
{
    if ((name) && (*name != '\0')) rframe::json_io::encodeObjectStart(sstr,name,indent);

    if ((name) && (*name != '\0')) rframe::json_io::encodeObjectEnd(sstr,indent,lastItem);
}

std::string nav_msgs::GetMapGoal::toStr(bool pretty) const
{

    stringstream sstr;
    string indent = (pretty == true) ? "\n" : "";

    rframe::json_io::encodeObjectStartMain(sstr,indent);
    rframe::json_io::encode(sstr,"",*this,indent,true);
    rframe::json_io::encodeObjectEnd(sstr,indent,true); // false so as to  not add , at end of string

    return sstr.str();

};

std::basic_ostream<char>& operator<<(std::basic_ostream<char> &s, const nav_msgs::GetMapGoal & value)
{
    return s << value.toStr(false);
}

