// 
//  AUTOGENERATED FILE:   do not edit
//
//  Generated by:         alex on alex-laptop, 2016-11-23 12:44:54 -0500
//  From Template/Script: data_templates/DataClassSerializationTemplate.cpp
 
/*
  CTA RIGHTS

  This document contains information proprietary to General Dynamics
  Robotic Systems and is not to be reproduced, transmitted, transferred,
  or otherwise used without the express written consent of General
  Dynamics Robotic Systems except as described below.

  GOVERNMENT PURPOSE RIGHTS

  Contract No.:        W911NF-10-2-0016, Articles of Collaboration,
                       Article 5, Intellectual Property
  Contractor Name:     General Dynamics Robotic Systems, Inc. (GDRS)
  Contractor Address:  1231 Tech Court, Westminster, MD  21157

  Expiration Date - None

  Technical data and computer software first created by Member(s) in
  performance of the Agreement will be disclosed to the Government.
  General Dynamics Robotic Systems retains the entire right, title, and
  interest throughout the world to each subject invention subject to the
  provisions of this clause and 37 CFR Part 401, 32 CFR 32.36, and
  34 CFR 34.25. The Government shall have the right to obtain, reproduce,
  publish or otherwise use the work for Government purposes.

  NON-EXCLUSIVE LICENSE TO CONSORTIUM PARTICIPANTS
  Consortium Members and subawardees are defined as 'Participants'
  Under Article 5.3, Participants are granted a nonexclusive, royalty-
  free, non-sublicenseable, non-assignable, license to Consortium
  Intellectual Property for the limited purpose of performing tasks under
  The Cooperative Agreement, for Government purposes only, and to make and
  have the same made solely for such use.

*/

#include <stdio.h>

// override the itemName template function used within serialization

#include <common/Log.h>
#include <common/BsonIo.h>
#include <common/SerializationCppHelpers.h>
#include <common/SerializationHelpers.h>

#include <sensor_msgs/BatteryState.h>
#include <sensor_msgs/CameraInfo.h>
#include <sensor_msgs/ChannelFloat32.h>
#include <sensor_msgs/CompressedImage.h>
#include <sensor_msgs/FluidPressure.h>
#include <sensor_msgs/Illuminance.h>
#include <sensor_msgs/Image.h>
#include <sensor_msgs/Imu.h>
#include <sensor_msgs/JointState.h>
#include <sensor_msgs/Joy.h>
#include <sensor_msgs/JoyFeedback.h>
#include <sensor_msgs/JoyFeedbackArray.h>
#include <sensor_msgs/LaserEcho.h>
#include <sensor_msgs/LaserScan.h>
#include <sensor_msgs/MagneticField.h>
#include <sensor_msgs/MultiDOFJointState.h>
#include <sensor_msgs/MultiEchoLaserScan.h>
#include <sensor_msgs/NavSatFix.h>
#include <sensor_msgs/NavSatStatus.h>
#include <sensor_msgs/PointCloud.h>
#include <sensor_msgs/PointCloud2.h>
#include <sensor_msgs/PointField.h>
#include <sensor_msgs/Range.h>
#include <sensor_msgs/RegionOfInterest.h>
#include <sensor_msgs/RelativeHumidity.h>
#include <sensor_msgs/Temperature.h>
#include <sensor_msgs/TimeReference.h>
#include <sensor_msgs/SetCameraInfoRequest.h>
#include <sensor_msgs/SetCameraInfoResponse.h>
#include <sensor_msgs/SetCameraInfo.h>

using namespace std;

template<class Archive> void sensor_msgs::BatteryState::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("header",header);

    ar & boost::serialization::make_nvp("voltage",voltage);

    ar & boost::serialization::make_nvp("current",current);

    ar & boost::serialization::make_nvp("charge",charge);

    ar & boost::serialization::make_nvp("capacity",capacity);

    ar & boost::serialization::make_nvp("design_capacity",design_capacity);

    ar & boost::serialization::make_nvp("percentage",percentage);

    ar & boost::serialization::make_nvp("power_supply_status",power_supply_status);

    ar & boost::serialization::make_nvp("power_supply_health",power_supply_health);

    ar & boost::serialization::make_nvp("power_supply_technology",power_supply_technology);

    ar & boost::serialization::make_nvp("present",present);

    ar & boost::serialization::make_nvp("cell_voltage",cell_voltage);

    ar & boost::serialization::make_nvp("location",location);

    ar & boost::serialization::make_nvp("serial_number",serial_number);
}

string sensor_msgs::BatteryState::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const sensor_msgs::BatteryState & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("BatteryState",robj);

    */
    string s = str.str();

    return s;
};

bool sensor_msgs::BatteryState::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    sensor_msgs::BatteryState & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("BatteryState",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(sensor_msgs::BatteryState); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(sensor_msgs::BatteryState); // defined in common/SerialzationHelpers.h

template<class Archive> void sensor_msgs::CameraInfo::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("header",header);

    ar & boost::serialization::make_nvp("height",height);

    ar & boost::serialization::make_nvp("width",width);

    ar & boost::serialization::make_nvp("distortion_model",distortion_model);

    ar & boost::serialization::make_nvp("D",D);// manually serialize arrays as the boost serialization code doesnt compile againt the type registry due to namespace issue
    {                                                                                            
        int count = 9;
        double * t = K.data();
        /*        string tempName;
        rframe::TypeRegistry &reg = rframe::TypeRegistry::instance();

        reg.lookupXMLName(tempName,typeid(double).name());*/

        while (0 < count--)
            ar & boost::serialization::make_nvp("item",*t++);
    }
    // manually serialize arrays as the boost serialization code doesnt compile againt the type registry due to namespace issue
    {                                                                                            
        int count = 9;
        double * t = R.data();
        /*        string tempName;
        rframe::TypeRegistry &reg = rframe::TypeRegistry::instance();

        reg.lookupXMLName(tempName,typeid(double).name());*/

        while (0 < count--)
            ar & boost::serialization::make_nvp("item",*t++);
    }
    // manually serialize arrays as the boost serialization code doesnt compile againt the type registry due to namespace issue
    {                                                                                            
        int count = 12;
        double * t = P.data();
        /*        string tempName;
        rframe::TypeRegistry &reg = rframe::TypeRegistry::instance();

        reg.lookupXMLName(tempName,typeid(double).name());*/

        while (0 < count--)
            ar & boost::serialization::make_nvp("item",*t++);
    }

    ar & boost::serialization::make_nvp("binning_x",binning_x);

    ar & boost::serialization::make_nvp("binning_y",binning_y);

    ar & boost::serialization::make_nvp("roi",roi);
}

string sensor_msgs::CameraInfo::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const sensor_msgs::CameraInfo & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("CameraInfo",robj);

    */
    string s = str.str();

    return s;
};

bool sensor_msgs::CameraInfo::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    sensor_msgs::CameraInfo & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("CameraInfo",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(sensor_msgs::CameraInfo); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(sensor_msgs::CameraInfo); // defined in common/SerialzationHelpers.h

template<class Archive> void sensor_msgs::ChannelFloat32::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("name",name);

    ar & boost::serialization::make_nvp("values",values);
}

string sensor_msgs::ChannelFloat32::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const sensor_msgs::ChannelFloat32 & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("ChannelFloat32",robj);

    */
    string s = str.str();

    return s;
};

bool sensor_msgs::ChannelFloat32::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    sensor_msgs::ChannelFloat32 & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("ChannelFloat32",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(sensor_msgs::ChannelFloat32); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(sensor_msgs::ChannelFloat32); // defined in common/SerialzationHelpers.h

template<class Archive> void sensor_msgs::CompressedImage::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("header",header);

    ar & boost::serialization::make_nvp("format",format);

    ar & boost::serialization::make_nvp("data",data);
}

string sensor_msgs::CompressedImage::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const sensor_msgs::CompressedImage & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("CompressedImage",robj);

    */
    string s = str.str();

    return s;
};

bool sensor_msgs::CompressedImage::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    sensor_msgs::CompressedImage & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("CompressedImage",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(sensor_msgs::CompressedImage); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(sensor_msgs::CompressedImage); // defined in common/SerialzationHelpers.h

template<class Archive> void sensor_msgs::FluidPressure::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("header",header);

    ar & boost::serialization::make_nvp("fluid_pressure",fluid_pressure);

    ar & boost::serialization::make_nvp("variance",variance);
}

string sensor_msgs::FluidPressure::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const sensor_msgs::FluidPressure & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("FluidPressure",robj);

    */
    string s = str.str();

    return s;
};

bool sensor_msgs::FluidPressure::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    sensor_msgs::FluidPressure & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("FluidPressure",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(sensor_msgs::FluidPressure); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(sensor_msgs::FluidPressure); // defined in common/SerialzationHelpers.h

template<class Archive> void sensor_msgs::Illuminance::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("header",header);

    ar & boost::serialization::make_nvp("illuminance",illuminance);

    ar & boost::serialization::make_nvp("variance",variance);
}

string sensor_msgs::Illuminance::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const sensor_msgs::Illuminance & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("Illuminance",robj);

    */
    string s = str.str();

    return s;
};

bool sensor_msgs::Illuminance::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    sensor_msgs::Illuminance & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("Illuminance",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(sensor_msgs::Illuminance); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(sensor_msgs::Illuminance); // defined in common/SerialzationHelpers.h

template<class Archive> void sensor_msgs::Image::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("header",header);

    ar & boost::serialization::make_nvp("height",height);

    ar & boost::serialization::make_nvp("width",width);

    ar & boost::serialization::make_nvp("encoding",encoding);

    ar & boost::serialization::make_nvp("is_bigendian",is_bigendian);

    ar & boost::serialization::make_nvp("step",step);

    ar & boost::serialization::make_nvp("data",data);
}

string sensor_msgs::Image::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const sensor_msgs::Image & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("Image",robj);

    */
    string s = str.str();

    return s;
};

bool sensor_msgs::Image::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    sensor_msgs::Image & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("Image",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(sensor_msgs::Image); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(sensor_msgs::Image); // defined in common/SerialzationHelpers.h

template<class Archive> void sensor_msgs::Imu::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("header",header);

    ar & boost::serialization::make_nvp("orientation",orientation);// manually serialize arrays as the boost serialization code doesnt compile againt the type registry due to namespace issue
    {                                                                                            
        int count = 9;
        double * t = orientation_covariance.data();
        /*        string tempName;
        rframe::TypeRegistry &reg = rframe::TypeRegistry::instance();

        reg.lookupXMLName(tempName,typeid(double).name());*/

        while (0 < count--)
            ar & boost::serialization::make_nvp("item",*t++);
    }

    ar & boost::serialization::make_nvp("angular_velocity",angular_velocity);// manually serialize arrays as the boost serialization code doesnt compile againt the type registry due to namespace issue
    {                                                                                            
        int count = 9;
        double * t = angular_velocity_covariance.data();
        /*        string tempName;
        rframe::TypeRegistry &reg = rframe::TypeRegistry::instance();

        reg.lookupXMLName(tempName,typeid(double).name());*/

        while (0 < count--)
            ar & boost::serialization::make_nvp("item",*t++);
    }

    ar & boost::serialization::make_nvp("linear_acceleration",linear_acceleration);// manually serialize arrays as the boost serialization code doesnt compile againt the type registry due to namespace issue
    {                                                                                            
        int count = 9;
        double * t = linear_acceleration_covariance.data();
        /*        string tempName;
        rframe::TypeRegistry &reg = rframe::TypeRegistry::instance();

        reg.lookupXMLName(tempName,typeid(double).name());*/

        while (0 < count--)
            ar & boost::serialization::make_nvp("item",*t++);
    }

}

string sensor_msgs::Imu::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const sensor_msgs::Imu & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("Imu",robj);

    */
    string s = str.str();

    return s;
};

bool sensor_msgs::Imu::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    sensor_msgs::Imu & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("Imu",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(sensor_msgs::Imu); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(sensor_msgs::Imu); // defined in common/SerialzationHelpers.h

template<class Archive> void sensor_msgs::JointState::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("header",header);

    ar & boost::serialization::make_nvp("name",name);

    ar & boost::serialization::make_nvp("position",position);

    ar & boost::serialization::make_nvp("velocity",velocity);

    ar & boost::serialization::make_nvp("effort",effort);
}

string sensor_msgs::JointState::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const sensor_msgs::JointState & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("JointState",robj);

    */
    string s = str.str();

    return s;
};

bool sensor_msgs::JointState::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    sensor_msgs::JointState & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("JointState",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(sensor_msgs::JointState); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(sensor_msgs::JointState); // defined in common/SerialzationHelpers.h

template<class Archive> void sensor_msgs::Joy::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("header",header);

    ar & boost::serialization::make_nvp("axes",axes);

    ar & boost::serialization::make_nvp("buttons",buttons);
}

string sensor_msgs::Joy::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const sensor_msgs::Joy & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("Joy",robj);

    */
    string s = str.str();

    return s;
};

bool sensor_msgs::Joy::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    sensor_msgs::Joy & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("Joy",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(sensor_msgs::Joy); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(sensor_msgs::Joy); // defined in common/SerialzationHelpers.h

template<class Archive> void sensor_msgs::JoyFeedback::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("type",type);

    ar & boost::serialization::make_nvp("id",id);

    ar & boost::serialization::make_nvp("intensity",intensity);
}

string sensor_msgs::JoyFeedback::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const sensor_msgs::JoyFeedback & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("JoyFeedback",robj);

    */
    string s = str.str();

    return s;
};

bool sensor_msgs::JoyFeedback::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    sensor_msgs::JoyFeedback & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("JoyFeedback",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(sensor_msgs::JoyFeedback); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(sensor_msgs::JoyFeedback); // defined in common/SerialzationHelpers.h

template<class Archive> void sensor_msgs::JoyFeedbackArray::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("array",array);
}

string sensor_msgs::JoyFeedbackArray::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const sensor_msgs::JoyFeedbackArray & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("JoyFeedbackArray",robj);

    */
    string s = str.str();

    return s;
};

bool sensor_msgs::JoyFeedbackArray::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    sensor_msgs::JoyFeedbackArray & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("JoyFeedbackArray",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(sensor_msgs::JoyFeedbackArray); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(sensor_msgs::JoyFeedbackArray); // defined in common/SerialzationHelpers.h

template<class Archive> void sensor_msgs::LaserEcho::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("echoes",echoes);
}

string sensor_msgs::LaserEcho::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const sensor_msgs::LaserEcho & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("LaserEcho",robj);

    */
    string s = str.str();

    return s;
};

bool sensor_msgs::LaserEcho::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    sensor_msgs::LaserEcho & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("LaserEcho",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(sensor_msgs::LaserEcho); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(sensor_msgs::LaserEcho); // defined in common/SerialzationHelpers.h

template<class Archive> void sensor_msgs::LaserScan::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("header",header);

    ar & boost::serialization::make_nvp("angle_min",angle_min);

    ar & boost::serialization::make_nvp("angle_max",angle_max);

    ar & boost::serialization::make_nvp("angle_increment",angle_increment);

    ar & boost::serialization::make_nvp("time_increment",time_increment);

    ar & boost::serialization::make_nvp("scan_time",scan_time);

    ar & boost::serialization::make_nvp("range_min",range_min);

    ar & boost::serialization::make_nvp("range_max",range_max);

    ar & boost::serialization::make_nvp("ranges",ranges);

    ar & boost::serialization::make_nvp("intensities",intensities);
}

string sensor_msgs::LaserScan::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const sensor_msgs::LaserScan & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("LaserScan",robj);

    */
    string s = str.str();

    return s;
};

bool sensor_msgs::LaserScan::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    sensor_msgs::LaserScan & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("LaserScan",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(sensor_msgs::LaserScan); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(sensor_msgs::LaserScan); // defined in common/SerialzationHelpers.h

template<class Archive> void sensor_msgs::MagneticField::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("header",header);

    ar & boost::serialization::make_nvp("magnetic_field",magnetic_field);// manually serialize arrays as the boost serialization code doesnt compile againt the type registry due to namespace issue
    {                                                                                            
        int count = 9;
        double * t = magnetic_field_covariance.data();
        /*        string tempName;
        rframe::TypeRegistry &reg = rframe::TypeRegistry::instance();

        reg.lookupXMLName(tempName,typeid(double).name());*/

        while (0 < count--)
            ar & boost::serialization::make_nvp("item",*t++);
    }

}

string sensor_msgs::MagneticField::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const sensor_msgs::MagneticField & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("MagneticField",robj);

    */
    string s = str.str();

    return s;
};

bool sensor_msgs::MagneticField::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    sensor_msgs::MagneticField & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("MagneticField",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(sensor_msgs::MagneticField); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(sensor_msgs::MagneticField); // defined in common/SerialzationHelpers.h

template<class Archive> void sensor_msgs::MultiDOFJointState::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("header",header);

    ar & boost::serialization::make_nvp("joint_names",joint_names);

    ar & boost::serialization::make_nvp("transforms",transforms);

    ar & boost::serialization::make_nvp("twist",twist);

    ar & boost::serialization::make_nvp("wrench",wrench);
}

string sensor_msgs::MultiDOFJointState::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const sensor_msgs::MultiDOFJointState & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("MultiDOFJointState",robj);

    */
    string s = str.str();

    return s;
};

bool sensor_msgs::MultiDOFJointState::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    sensor_msgs::MultiDOFJointState & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("MultiDOFJointState",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(sensor_msgs::MultiDOFJointState); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(sensor_msgs::MultiDOFJointState); // defined in common/SerialzationHelpers.h

template<class Archive> void sensor_msgs::MultiEchoLaserScan::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("header",header);

    ar & boost::serialization::make_nvp("angle_min",angle_min);

    ar & boost::serialization::make_nvp("angle_max",angle_max);

    ar & boost::serialization::make_nvp("angle_increment",angle_increment);

    ar & boost::serialization::make_nvp("time_increment",time_increment);

    ar & boost::serialization::make_nvp("scan_time",scan_time);

    ar & boost::serialization::make_nvp("range_min",range_min);

    ar & boost::serialization::make_nvp("range_max",range_max);

    ar & boost::serialization::make_nvp("ranges",ranges);

    ar & boost::serialization::make_nvp("intensities",intensities);
}

string sensor_msgs::MultiEchoLaserScan::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const sensor_msgs::MultiEchoLaserScan & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("MultiEchoLaserScan",robj);

    */
    string s = str.str();

    return s;
};

bool sensor_msgs::MultiEchoLaserScan::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    sensor_msgs::MultiEchoLaserScan & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("MultiEchoLaserScan",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(sensor_msgs::MultiEchoLaserScan); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(sensor_msgs::MultiEchoLaserScan); // defined in common/SerialzationHelpers.h

template<class Archive> void sensor_msgs::NavSatFix::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("header",header);

    ar & boost::serialization::make_nvp("status",status);

    ar & boost::serialization::make_nvp("latitude",latitude);

    ar & boost::serialization::make_nvp("longitude",longitude);

    ar & boost::serialization::make_nvp("altitude",altitude);// manually serialize arrays as the boost serialization code doesnt compile againt the type registry due to namespace issue
    {                                                                                            
        int count = 9;
        double * t = position_covariance.data();
        /*        string tempName;
        rframe::TypeRegistry &reg = rframe::TypeRegistry::instance();

        reg.lookupXMLName(tempName,typeid(double).name());*/

        while (0 < count--)
            ar & boost::serialization::make_nvp("item",*t++);
    }

    ar & boost::serialization::make_nvp("position_covariance_type",position_covariance_type);
}

string sensor_msgs::NavSatFix::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const sensor_msgs::NavSatFix & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("NavSatFix",robj);

    */
    string s = str.str();

    return s;
};

bool sensor_msgs::NavSatFix::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    sensor_msgs::NavSatFix & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("NavSatFix",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(sensor_msgs::NavSatFix); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(sensor_msgs::NavSatFix); // defined in common/SerialzationHelpers.h

template<class Archive> void sensor_msgs::NavSatStatus::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("status",status);

    ar & boost::serialization::make_nvp("service",service);
}

string sensor_msgs::NavSatStatus::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const sensor_msgs::NavSatStatus & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("NavSatStatus",robj);

    */
    string s = str.str();

    return s;
};

bool sensor_msgs::NavSatStatus::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    sensor_msgs::NavSatStatus & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("NavSatStatus",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(sensor_msgs::NavSatStatus); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(sensor_msgs::NavSatStatus); // defined in common/SerialzationHelpers.h

template<class Archive> void sensor_msgs::PointCloud::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("header",header);

    ar & boost::serialization::make_nvp("points",points);

    ar & boost::serialization::make_nvp("channels",channels);
}

string sensor_msgs::PointCloud::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const sensor_msgs::PointCloud & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("PointCloud",robj);

    */
    string s = str.str();

    return s;
};

bool sensor_msgs::PointCloud::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    sensor_msgs::PointCloud & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("PointCloud",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(sensor_msgs::PointCloud); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(sensor_msgs::PointCloud); // defined in common/SerialzationHelpers.h

template<class Archive> void sensor_msgs::PointCloud2::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("header",header);

    ar & boost::serialization::make_nvp("height",height);

    ar & boost::serialization::make_nvp("width",width);

    ar & boost::serialization::make_nvp("fields",fields);

    ar & boost::serialization::make_nvp("is_bigendian",is_bigendian);

    ar & boost::serialization::make_nvp("point_step",point_step);

    ar & boost::serialization::make_nvp("row_step",row_step);

    ar & boost::serialization::make_nvp("data",data);

    ar & boost::serialization::make_nvp("is_dense",is_dense);
}

string sensor_msgs::PointCloud2::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const sensor_msgs::PointCloud2 & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("PointCloud2",robj);

    */
    string s = str.str();

    return s;
};

bool sensor_msgs::PointCloud2::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    sensor_msgs::PointCloud2 & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("PointCloud2",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(sensor_msgs::PointCloud2); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(sensor_msgs::PointCloud2); // defined in common/SerialzationHelpers.h

template<class Archive> void sensor_msgs::PointField::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("name",name);

    ar & boost::serialization::make_nvp("offset",offset);

    ar & boost::serialization::make_nvp("datatype",datatype);

    ar & boost::serialization::make_nvp("count",count);
}

string sensor_msgs::PointField::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const sensor_msgs::PointField & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("PointField",robj);

    */
    string s = str.str();

    return s;
};

bool sensor_msgs::PointField::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    sensor_msgs::PointField & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("PointField",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(sensor_msgs::PointField); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(sensor_msgs::PointField); // defined in common/SerialzationHelpers.h

template<class Archive> void sensor_msgs::Range::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("header",header);

    ar & boost::serialization::make_nvp("radiation_type",radiation_type);

    ar & boost::serialization::make_nvp("field_of_view",field_of_view);

    ar & boost::serialization::make_nvp("min_range",min_range);

    ar & boost::serialization::make_nvp("max_range",max_range);

    ar & boost::serialization::make_nvp("range",range);
}

string sensor_msgs::Range::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const sensor_msgs::Range & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("Range",robj);

    */
    string s = str.str();

    return s;
};

bool sensor_msgs::Range::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    sensor_msgs::Range & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("Range",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(sensor_msgs::Range); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(sensor_msgs::Range); // defined in common/SerialzationHelpers.h

template<class Archive> void sensor_msgs::RegionOfInterest::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("x_offset",x_offset);

    ar & boost::serialization::make_nvp("y_offset",y_offset);

    ar & boost::serialization::make_nvp("height",height);

    ar & boost::serialization::make_nvp("width",width);

    ar & boost::serialization::make_nvp("do_rectify",do_rectify);
}

string sensor_msgs::RegionOfInterest::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const sensor_msgs::RegionOfInterest & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("RegionOfInterest",robj);

    */
    string s = str.str();

    return s;
};

bool sensor_msgs::RegionOfInterest::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    sensor_msgs::RegionOfInterest & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("RegionOfInterest",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(sensor_msgs::RegionOfInterest); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(sensor_msgs::RegionOfInterest); // defined in common/SerialzationHelpers.h

template<class Archive> void sensor_msgs::RelativeHumidity::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("header",header);

    ar & boost::serialization::make_nvp("relative_humidity",relative_humidity);

    ar & boost::serialization::make_nvp("variance",variance);
}

string sensor_msgs::RelativeHumidity::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const sensor_msgs::RelativeHumidity & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("RelativeHumidity",robj);

    */
    string s = str.str();

    return s;
};

bool sensor_msgs::RelativeHumidity::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    sensor_msgs::RelativeHumidity & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("RelativeHumidity",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(sensor_msgs::RelativeHumidity); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(sensor_msgs::RelativeHumidity); // defined in common/SerialzationHelpers.h

template<class Archive> void sensor_msgs::Temperature::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("header",header);

    ar & boost::serialization::make_nvp("temperature",temperature);

    ar & boost::serialization::make_nvp("variance",variance);
}

string sensor_msgs::Temperature::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const sensor_msgs::Temperature & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("Temperature",robj);

    */
    string s = str.str();

    return s;
};

bool sensor_msgs::Temperature::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    sensor_msgs::Temperature & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("Temperature",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(sensor_msgs::Temperature); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(sensor_msgs::Temperature); // defined in common/SerialzationHelpers.h

template<class Archive> void sensor_msgs::TimeReference::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("header",header);

    ar & boost::serialization::make_nvp("time_ref",time_ref);

    ar & boost::serialization::make_nvp("source",source);
}

string sensor_msgs::TimeReference::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const sensor_msgs::TimeReference & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("TimeReference",robj);

    */
    string s = str.str();

    return s;
};

bool sensor_msgs::TimeReference::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    sensor_msgs::TimeReference & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("TimeReference",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(sensor_msgs::TimeReference); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(sensor_msgs::TimeReference); // defined in common/SerialzationHelpers.h

template<class Archive> void sensor_msgs::SetCameraInfoRequest::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("camera_info",camera_info);
}

string sensor_msgs::SetCameraInfoRequest::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const sensor_msgs::SetCameraInfoRequest & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("SetCameraInfoRequest",robj);

    */
    string s = str.str();

    return s;
};

bool sensor_msgs::SetCameraInfoRequest::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    sensor_msgs::SetCameraInfoRequest & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("SetCameraInfoRequest",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(sensor_msgs::SetCameraInfoRequest); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(sensor_msgs::SetCameraInfoRequest); // defined in common/SerialzationHelpers.h

template<class Archive> void sensor_msgs::SetCameraInfoResponse::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("success",success);

    ar & boost::serialization::make_nvp("status_message",status_message);
}

string sensor_msgs::SetCameraInfoResponse::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const sensor_msgs::SetCameraInfoResponse & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("SetCameraInfoResponse",robj);

    */
    string s = str.str();

    return s;
};

bool sensor_msgs::SetCameraInfoResponse::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    sensor_msgs::SetCameraInfoResponse & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("SetCameraInfoResponse",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(sensor_msgs::SetCameraInfoResponse); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(sensor_msgs::SetCameraInfoResponse); // defined in common/SerialzationHelpers.h

template<class Archive> void sensor_msgs::SetCameraInfo::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("request",request);

    ar & boost::serialization::make_nvp("response",response);
}

string sensor_msgs::SetCameraInfo::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const sensor_msgs::SetCameraInfo & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("SetCameraInfo",robj);

    */
    string s = str.str();

    return s;
};

bool sensor_msgs::SetCameraInfo::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    sensor_msgs::SetCameraInfo & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("SetCameraInfo",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(sensor_msgs::SetCameraInfo); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(sensor_msgs::SetCameraInfo); // defined in common/SerialzationHelpers.h

