// 
//  AUTOGENERATED FILE:   do not edit
//
//  Generated by:         yongbo on yongbo-XPS-15-9550, 2017-01-26 15:57:06 -0500
//  From Template/Script: data_templates/DataClassSerializationTemplate.cpp
 
/*
  CTA RIGHTS

  This document contains information proprietary to General Dynamics
  Robotic Systems and is not to be reproduced, transmitted, transferred,
  or otherwise used without the express written consent of General
  Dynamics Robotic Systems except as described below.

  GOVERNMENT PURPOSE RIGHTS

  Contract No.:        W911NF-10-2-0016, Articles of Collaboration,
                       Article 5, Intellectual Property
  Contractor Name:     General Dynamics Robotic Systems, Inc. (GDRS)
  Contractor Address:  1231 Tech Court, Westminster, MD  21157

  Expiration Date - None

  Technical data and computer software first created by Member(s) in
  performance of the Agreement will be disclosed to the Government.
  General Dynamics Robotic Systems retains the entire right, title, and
  interest throughout the world to each subject invention subject to the
  provisions of this clause and 37 CFR Part 401, 32 CFR 32.36, and
  34 CFR 34.25. The Government shall have the right to obtain, reproduce,
  publish or otherwise use the work for Government purposes.

  NON-EXCLUSIVE LICENSE TO CONSORTIUM PARTICIPANTS
  Consortium Members and subawardees are defined as 'Participants'
  Under Article 5.3, Participants are granted a nonexclusive, royalty-
  free, non-sublicenseable, non-assignable, license to Consortium
  Intellectual Property for the limited purpose of performing tasks under
  The Cooperative Agreement, for Government purposes only, and to make and
  have the same made solely for such use.

*/

#include <stdio.h>

// override the itemName template function used within serialization

#include <common/Log.h>
#include <common/BsonIo.h>
#include <common/SerializationCppHelpers.h>
#include <common/SerializationHelpers.h>

#include <map_msgs/OccupancyGridUpdate.h>
#include <map_msgs/PointCloud2Update.h>
#include <map_msgs/ProjectedMap.h>
#include <map_msgs/ProjectedMapInfo.h>
#include <map_msgs/GetMapROIRequest.h>
#include <map_msgs/GetMapROIResponse.h>
#include <map_msgs/GetMapROI.h>
#include <map_msgs/GetPointMapRequest.h>
#include <map_msgs/GetPointMapResponse.h>
#include <map_msgs/GetPointMap.h>
#include <map_msgs/GetPointMapROIRequest.h>
#include <map_msgs/GetPointMapROIResponse.h>
#include <map_msgs/GetPointMapROI.h>
#include <map_msgs/ProjectedMapsInfo.h>
#include <map_msgs/SaveMap.h>
#include <map_msgs/SetMapProjectionsRequest.h>
#include <map_msgs/SetMapProjectionsResponse.h>
#include <map_msgs/SetMapProjections.h>

using namespace std;

template<class Archive> void map_msgs::OccupancyGridUpdate::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("header",header);

    ar & boost::serialization::make_nvp("x",x);

    ar & boost::serialization::make_nvp("y",y);

    ar & boost::serialization::make_nvp("width",width);

    ar & boost::serialization::make_nvp("height",height);

    ar & boost::serialization::make_nvp("data",data);
}

string map_msgs::OccupancyGridUpdate::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const map_msgs::OccupancyGridUpdate & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("OccupancyGridUpdate",robj);

    */
    string s = str.str();

    return s;
};

bool map_msgs::OccupancyGridUpdate::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    map_msgs::OccupancyGridUpdate & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("OccupancyGridUpdate",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(map_msgs::OccupancyGridUpdate); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(map_msgs::OccupancyGridUpdate); // defined in common/SerialzationHelpers.h

template<class Archive> void map_msgs::PointCloud2Update::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("header",header);

    ar & boost::serialization::make_nvp("type",type);

    ar & boost::serialization::make_nvp("points",points);
}

string map_msgs::PointCloud2Update::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const map_msgs::PointCloud2Update & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("PointCloud2Update",robj);

    */
    string s = str.str();

    return s;
};

bool map_msgs::PointCloud2Update::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    map_msgs::PointCloud2Update & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("PointCloud2Update",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(map_msgs::PointCloud2Update); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(map_msgs::PointCloud2Update); // defined in common/SerialzationHelpers.h

template<class Archive> void map_msgs::ProjectedMap::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("map",map);

    ar & boost::serialization::make_nvp("min_z",min_z);

    ar & boost::serialization::make_nvp("max_z",max_z);
}

string map_msgs::ProjectedMap::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const map_msgs::ProjectedMap & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("ProjectedMap",robj);

    */
    string s = str.str();

    return s;
};

bool map_msgs::ProjectedMap::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    map_msgs::ProjectedMap & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("ProjectedMap",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(map_msgs::ProjectedMap); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(map_msgs::ProjectedMap); // defined in common/SerialzationHelpers.h

template<class Archive> void map_msgs::ProjectedMapInfo::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("frame_id",frame_id);

    ar & boost::serialization::make_nvp("x",x);

    ar & boost::serialization::make_nvp("y",y);

    ar & boost::serialization::make_nvp("width",width);

    ar & boost::serialization::make_nvp("height",height);

    ar & boost::serialization::make_nvp("min_z",min_z);

    ar & boost::serialization::make_nvp("max_z",max_z);
}

string map_msgs::ProjectedMapInfo::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const map_msgs::ProjectedMapInfo & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("ProjectedMapInfo",robj);

    */
    string s = str.str();

    return s;
};

bool map_msgs::ProjectedMapInfo::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    map_msgs::ProjectedMapInfo & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("ProjectedMapInfo",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(map_msgs::ProjectedMapInfo); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(map_msgs::ProjectedMapInfo); // defined in common/SerialzationHelpers.h

template<class Archive> void map_msgs::GetMapROIRequest::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("x",x);

    ar & boost::serialization::make_nvp("y",y);

    ar & boost::serialization::make_nvp("l_x",l_x);

    ar & boost::serialization::make_nvp("l_y",l_y);
}

string map_msgs::GetMapROIRequest::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const map_msgs::GetMapROIRequest & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("GetMapROIRequest",robj);

    */
    string s = str.str();

    return s;
};

bool map_msgs::GetMapROIRequest::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    map_msgs::GetMapROIRequest & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("GetMapROIRequest",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(map_msgs::GetMapROIRequest); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(map_msgs::GetMapROIRequest); // defined in common/SerialzationHelpers.h

template<class Archive> void map_msgs::GetMapROIResponse::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("sub_map",sub_map);
}

string map_msgs::GetMapROIResponse::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const map_msgs::GetMapROIResponse & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("GetMapROIResponse",robj);

    */
    string s = str.str();

    return s;
};

bool map_msgs::GetMapROIResponse::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    map_msgs::GetMapROIResponse & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("GetMapROIResponse",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(map_msgs::GetMapROIResponse); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(map_msgs::GetMapROIResponse); // defined in common/SerialzationHelpers.h

template<class Archive> void map_msgs::GetMapROI::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("request",request);

    ar & boost::serialization::make_nvp("response",response);
}

string map_msgs::GetMapROI::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const map_msgs::GetMapROI & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("GetMapROI",robj);

    */
    string s = str.str();

    return s;
};

bool map_msgs::GetMapROI::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    map_msgs::GetMapROI & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("GetMapROI",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(map_msgs::GetMapROI); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(map_msgs::GetMapROI); // defined in common/SerialzationHelpers.h

template<class Archive> void map_msgs::GetPointMapRequest::serialize(Archive &ar, const unsigned int fileVersion)
{   

}

string map_msgs::GetPointMapRequest::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const map_msgs::GetPointMapRequest & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("GetPointMapRequest",robj);

    */
    string s = str.str();

    return s;
};

bool map_msgs::GetPointMapRequest::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    map_msgs::GetPointMapRequest & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("GetPointMapRequest",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(map_msgs::GetPointMapRequest); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(map_msgs::GetPointMapRequest); // defined in common/SerialzationHelpers.h

template<class Archive> void map_msgs::GetPointMapResponse::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("map",map);
}

string map_msgs::GetPointMapResponse::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const map_msgs::GetPointMapResponse & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("GetPointMapResponse",robj);

    */
    string s = str.str();

    return s;
};

bool map_msgs::GetPointMapResponse::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    map_msgs::GetPointMapResponse & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("GetPointMapResponse",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(map_msgs::GetPointMapResponse); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(map_msgs::GetPointMapResponse); // defined in common/SerialzationHelpers.h

template<class Archive> void map_msgs::GetPointMap::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("request",request);

    ar & boost::serialization::make_nvp("response",response);
}

string map_msgs::GetPointMap::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const map_msgs::GetPointMap & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("GetPointMap",robj);

    */
    string s = str.str();

    return s;
};

bool map_msgs::GetPointMap::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    map_msgs::GetPointMap & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("GetPointMap",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(map_msgs::GetPointMap); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(map_msgs::GetPointMap); // defined in common/SerialzationHelpers.h

template<class Archive> void map_msgs::GetPointMapROIRequest::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("x",x);

    ar & boost::serialization::make_nvp("y",y);

    ar & boost::serialization::make_nvp("z",z);

    ar & boost::serialization::make_nvp("r",r);

    ar & boost::serialization::make_nvp("l_x",l_x);

    ar & boost::serialization::make_nvp("l_y",l_y);

    ar & boost::serialization::make_nvp("l_z",l_z);
}

string map_msgs::GetPointMapROIRequest::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const map_msgs::GetPointMapROIRequest & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("GetPointMapROIRequest",robj);

    */
    string s = str.str();

    return s;
};

bool map_msgs::GetPointMapROIRequest::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    map_msgs::GetPointMapROIRequest & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("GetPointMapROIRequest",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(map_msgs::GetPointMapROIRequest); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(map_msgs::GetPointMapROIRequest); // defined in common/SerialzationHelpers.h

template<class Archive> void map_msgs::GetPointMapROIResponse::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("sub_map",sub_map);
}

string map_msgs::GetPointMapROIResponse::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const map_msgs::GetPointMapROIResponse & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("GetPointMapROIResponse",robj);

    */
    string s = str.str();

    return s;
};

bool map_msgs::GetPointMapROIResponse::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    map_msgs::GetPointMapROIResponse & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("GetPointMapROIResponse",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(map_msgs::GetPointMapROIResponse); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(map_msgs::GetPointMapROIResponse); // defined in common/SerialzationHelpers.h

template<class Archive> void map_msgs::GetPointMapROI::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("request",request);

    ar & boost::serialization::make_nvp("response",response);
}

string map_msgs::GetPointMapROI::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const map_msgs::GetPointMapROI & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("GetPointMapROI",robj);

    */
    string s = str.str();

    return s;
};

bool map_msgs::GetPointMapROI::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    map_msgs::GetPointMapROI & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("GetPointMapROI",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(map_msgs::GetPointMapROI); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(map_msgs::GetPointMapROI); // defined in common/SerialzationHelpers.h

template<class Archive> void map_msgs::ProjectedMapsInfo::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("projected_maps_info",projected_maps_info);
}

string map_msgs::ProjectedMapsInfo::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const map_msgs::ProjectedMapsInfo & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("ProjectedMapsInfo",robj);

    */
    string s = str.str();

    return s;
};

bool map_msgs::ProjectedMapsInfo::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    map_msgs::ProjectedMapsInfo & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("ProjectedMapsInfo",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(map_msgs::ProjectedMapsInfo); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(map_msgs::ProjectedMapsInfo); // defined in common/SerialzationHelpers.h

template<class Archive> void map_msgs::SaveMap::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("filename",filename);
}

string map_msgs::SaveMap::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const map_msgs::SaveMap & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("SaveMap",robj);

    */
    string s = str.str();

    return s;
};

bool map_msgs::SaveMap::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    map_msgs::SaveMap & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("SaveMap",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(map_msgs::SaveMap); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(map_msgs::SaveMap); // defined in common/SerialzationHelpers.h

template<class Archive> void map_msgs::SetMapProjectionsRequest::serialize(Archive &ar, const unsigned int fileVersion)
{   

}

string map_msgs::SetMapProjectionsRequest::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const map_msgs::SetMapProjectionsRequest & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("SetMapProjectionsRequest",robj);

    */
    string s = str.str();

    return s;
};

bool map_msgs::SetMapProjectionsRequest::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    map_msgs::SetMapProjectionsRequest & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("SetMapProjectionsRequest",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(map_msgs::SetMapProjectionsRequest); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(map_msgs::SetMapProjectionsRequest); // defined in common/SerialzationHelpers.h

template<class Archive> void map_msgs::SetMapProjectionsResponse::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("projected_maps_info",projected_maps_info);
}

string map_msgs::SetMapProjectionsResponse::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const map_msgs::SetMapProjectionsResponse & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("SetMapProjectionsResponse",robj);

    */
    string s = str.str();

    return s;
};

bool map_msgs::SetMapProjectionsResponse::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    map_msgs::SetMapProjectionsResponse & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("SetMapProjectionsResponse",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(map_msgs::SetMapProjectionsResponse); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(map_msgs::SetMapProjectionsResponse); // defined in common/SerialzationHelpers.h

template<class Archive> void map_msgs::SetMapProjections::serialize(Archive &ar, const unsigned int fileVersion)
{   

    ar & boost::serialization::make_nvp("request",request);

    ar & boost::serialization::make_nvp("response",response);
}

string map_msgs::SetMapProjections::toXML() const
{
    stringstream str;
    std::cout << "toXML commented out" << std::endl;
    /*
    const map_msgs::SetMapProjections & robj = (*this);

    boost::archive::xml_oarchive oa(str,boost::archive::no_header);
    oa & boost::serialization::make_nvp("SetMapProjections",robj);

    */
    string s = str.str();

    return s;
};

bool map_msgs::SetMapProjections::fromXML(const string &str)
{
    bool retval = true;
        std::cout << "fromXML commented out" << std::endl;
    /*
    stringstream sstr(str);
    map_msgs::SetMapProjections & robj = (*this);

    try
    {
        boost::archive::xml_iarchive oa(sstr,boost::archive::no_header);
        oa & boost::serialization::make_nvp("SetMapProjections",robj);
    }
    catch (exception & e)
    {
        retval = false;
    }

    */
    return retval;
};

GENERIC_SERIALIZATION_ENTRYPOINTS(map_msgs::SetMapProjections); // defined in common/Common.h

INSTANTIATE_BOOST_SERIALIZATION(map_msgs::SetMapProjections); // defined in common/SerialzationHelpers.h

