// 
//  AUTOGENERATED FILE:   do not edit
//
//  Generated by:         yongbo on yongbo-XPS-15-9550, 2017-01-26 15:57:08 -0500
//  From Template/Script: data_templates/DataClassTemplate.cpp
 
/*
  CTA RIGHTS

  This document contains information proprietary to General Dynamics
  Robotic Systems and is not to be reproduced, transmitted, transferred,
  or otherwise used without the express written consent of General
  Dynamics Robotic Systems except as described below.

  GOVERNMENT PURPOSE RIGHTS

  Contract No.:        W911NF-10-2-0016, Articles of Collaboration,
                       Article 5, Intellectual Property
  Contractor Name:     General Dynamics Robotic Systems, Inc. (GDRS)
  Contractor Address:  1231 Tech Court, Westminster, MD  21157

  Expiration Date - None

  Technical data and computer software first created by Member(s) in
  performance of the Agreement will be disclosed to the Government.
  General Dynamics Robotic Systems retains the entire right, title, and
  interest throughout the world to each subject invention subject to the
  provisions of this clause and 37 CFR Part 401, 32 CFR 32.36, and
  34 CFR 34.25. The Government shall have the right to obtain, reproduce,
  publish or otherwise use the work for Government purposes.

  NON-EXCLUSIVE LICENSE TO CONSORTIUM PARTICIPANTS
  Consortium Members and subawardees are defined as 'Participants'
  Under Article 5.3, Participants are granted a nonexclusive, royalty-
  free, non-sublicenseable, non-assignable, license to Consortium
  Intellectual Property for the limited purpose of performing tasks under
  The Cooperative Agreement, for Government purposes only, and to make and
  have the same made solely for such use.

*/

#include <math.h> // to allow use of common constants...
#include <common/Error.h>
#include "theora_image_transport/Packet.h"

#include <common/JsonIo.h> // include here so container types are included by the class header 

using namespace std;

const unsigned int theora_image_transport::Packet::ID;
const unsigned int theora_image_transport::Packet::DATA_VERSION;
const std::string theora_image_transport::Packet::DATA_TYPE_NAME = "Packet";
const std::string theora_image_transport::Packet::DATA_TYPE_FULL_NAME = "theora_image_transport::Packet";
const std::string theora_image_transport::Packet::VERSION_MD5 = "1bfd489efb319c781dbaadbb1df96c7d";
/* xml source for this class */
const std::string theora_image_transport::Packet::XML_SOURCE = "<class name=\"Packet\" publicDataMembers=\"true\" sourceIDL=\"ROS\" ros=\"true\" rosMD5=\"33ac4e14a7cff32e7e0d65f18bb410f3\" rosDesc=\"# ROS message adaptation of the ogg_packet struct from libogg,\\n# see http://www.xiph.org/ogg/doc/libogg/ogg_packet.html.\\n\\nHeader header     # Original sensor_msgs/Image header\\nuint8[] data      # Raw Theora packet data (combines packet and bytes fields from ogg_packet)\\nint32 b_o_s       # Flag indicating whether this packet begins a logical bitstream\\nint32 e_o_s       # Flag indicating whether this packet ends a bitstream\\nint64 granulepos  # A number indicating the position of this packet in the decoded data\\nint64 packetno    # Sequential number of this packet in the ogg bitstream\\n\\n================================================================================\\nMSG: std_msgs/Header\\n# Standard metadata for higher-level stamped data types.\\n# This is generally used to communicate timestamped data \\n# in a particular coordinate frame.\\n# \\n# sequence ID: consecutively increasing ID \\nuint32 seq\\n#Two-integer timestamp that is expressed as:\\n# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\\n# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\\n# time-handling sugar is provided by the client library\\ntime stamp\\n#Frame this data is associated with\\n# 0: no frame\\n# 1: global frame\\nstring frame_id\\n\" comment=\"ROS message adaptation of the ogg_packet struct from libogg,  see http://www.xiph.org/ogg/doc/libogg/ogg_packet.html.\" id=\"1125733595\">\
  <field name=\"header\" type=\"std_msgs::Header\" sourceType=\"Header\" comment=\"Original sensor_msgs/Image header\"/>\
  <field name=\"data\" type=\"vector(unsigned char)\" sourceType=\"uint8\" comment=\"Raw Theora packet data (combines packet and bytes fields from ogg_packet)\"/>\
  <field name=\"b_o_s\" type=\"int\" sourceType=\"int32\" comment=\"Flag indicating whether this packet begins a logical bitstream\"/>\
  <field name=\"e_o_s\" type=\"int\" sourceType=\"int32\" comment=\"Flag indicating whether this packet ends a bitstream\"/>\
  <field name=\"granulepos\" type=\"long long int\" sourceType=\"int64\" comment=\"A number indicating the position of this packet in the decoded data\"/>\
  <field name=\"packetno\" type=\"long long int\" sourceType=\"int64\" comment=\"Sequential number of this packet in the ogg bitstream\"/>\
</class>";

theora_image_transport::Packet::Packet() : header(), data(), b_o_s(0), e_o_s(0), granulepos(0), packetno(0)
{  
};

theora_image_transport::Packet::Packet(const theora_image_transport::Packet & inobj) : header(inobj.header), data(inobj.data), b_o_s(inobj.b_o_s), e_o_s(inobj.e_o_s), granulepos(inobj.granulepos), packetno(inobj.packetno)
{
};

theora_image_transport::Packet::~Packet()
{
};

theora_image_transport::Packet * theora_image_transport::Packet::New()
{ 
    return new Packet();
};

bool theora_image_transport::Packet::dataTypeFlat() 
{   
    return false; 
};

theora_image_transport::Packet & theora_image_transport::Packet::operator=(const theora_image_transport::Packet & inobj)
{
    if (this != &inobj)
    {

        // if datatype is flat, optimize with memcpy (complier level optimiation)
              /*  if (dataTypeFlat() == true)
                  REMOVED invalid when assigning from a parent type as this is the pointer to the derived type, thus theora_image_transport::Packet is copied to the wrong location

        {
            memcpy(this,&inobj,sizeof(theora_image_transport::Packet));
        }
        else */ 
        {

            header = inobj.header;
            data = inobj.data;
            b_o_s = inobj.b_o_s;
            e_o_s = inobj.e_o_s;
            granulepos = inobj.granulepos;
            packetno = inobj.packetno;
        }
    }

    return *this;
}

bool theora_image_transport::Packet::operator==(const theora_image_transport::Packet & inobj) const
{
    bool ret = true;

    if (this != &inobj)
    { 
        ret = ret 
             && (header == inobj.header)
             && (data == inobj.data)
             && (b_o_s == inobj.b_o_s)
             && (e_o_s == inobj.e_o_s)
             && (granulepos == inobj.granulepos)
             && (packetno == inobj.packetno);
    }

    return ret;
}

bool theora_image_transport::Packet::operator!=(const theora_image_transport::Packet & inobj) const
{
    bool ret = false;

    if (this != &inobj)
    {
        ret = !operator==(inobj);
    }

    return ret;
}

bool theora_image_transport::Packet::operator<(const theora_image_transport::Packet & inobj) const
{
    bool ret = false;

    if (this == &inobj)
    {
        ret = false;
    }
    else
    {  
        // comparison algorithm based on std::lexicographical_compare algorithm

        if (header < inobj.header) return true;
        if (inobj.header <  header) return false; 
        if (data < inobj.data) return true;
        if (inobj.data <  data) return false; 
        if (b_o_s < inobj.b_o_s) return true;
        if (inobj.b_o_s <  b_o_s) return false; 
        if (e_o_s < inobj.e_o_s) return true;
        if (inobj.e_o_s <  e_o_s) return false; 
        if (granulepos < inobj.granulepos) return true;
        if (inobj.granulepos <  granulepos) return false; 
        if (packetno < inobj.packetno) return true;
        if (inobj.packetno <  packetno) return false; ;
    }

    return ret;
}

bool theora_image_transport::Packet::operator>(const theora_image_transport::Packet & inobj) const
{
    bool ret = false;

    if (this == &inobj)
    {
        ret = false;
    }
    else
    {
        // comparison algorithm based on std::lexicographical_compare algorithm

        if (header > inobj.header) return true;
        if (inobj.header >  header) return false; 
        if (data > inobj.data) return true;
        if (inobj.data >  data) return false; 
        if (b_o_s > inobj.b_o_s) return true;
        if (inobj.b_o_s >  b_o_s) return false; 
        if (e_o_s > inobj.e_o_s) return true;
        if (inobj.e_o_s >  e_o_s) return false; 
        if (granulepos > inobj.granulepos) return true;
        if (inobj.granulepos >  granulepos) return false; 
        if (packetno > inobj.packetno) return true;
        if (inobj.packetno >  packetno) return false; ;
    }

    return ret;
}

template <> void rframe::json_io::encode(std::stringstream & sstr, const char * name, const theora_image_transport::Packet & t, std::string & indent, bool lastItem)
{
    if ((name) && (*name != '\0')) rframe::json_io::encodeObjectStart(sstr,name,indent);

    rframe::json_io::encode(sstr,"header",t.header,indent,false);
    rframe::json_io::encode(sstr,"data",t.data,indent,false);
    rframe::json_io::encode(sstr,"b_o_s",t.b_o_s,indent,false);
    rframe::json_io::encode(sstr,"e_o_s",t.e_o_s,indent,false);
    rframe::json_io::encode(sstr,"granulepos",t.granulepos,indent,false);
    rframe::json_io::encode(sstr,"packetno",t.packetno,indent,true);

    if ((name) && (*name != '\0')) rframe::json_io::encodeObjectEnd(sstr,indent,lastItem);
}

std::string theora_image_transport::Packet::toStr(bool pretty) const
{

    stringstream sstr;
    string indent = (pretty == true) ? "\n" : "";

    rframe::json_io::encodeObjectStartMain(sstr,indent);
    rframe::json_io::encode(sstr,"",*this,indent,true);
    rframe::json_io::encodeObjectEnd(sstr,indent,true); // false so as to  not add , at end of string

    return sstr.str();

};

std::basic_ostream<char>& operator<<(std::basic_ostream<char> &s, const theora_image_transport::Packet & value)
{
    return s << value.toStr(false);
}

