// 
//  AUTOGENERATED FILE:   do not edit
//
//  Generated by:         yongbo on yongbo-XPS-15-9550, 2017-01-26 15:57:09 -0500
//  From Template/Script: data_templates/DataClassTemplate.cpp
 
/*
  CTA RIGHTS

  This document contains information proprietary to General Dynamics
  Robotic Systems and is not to be reproduced, transmitted, transferred,
  or otherwise used without the express written consent of General
  Dynamics Robotic Systems except as described below.

  GOVERNMENT PURPOSE RIGHTS

  Contract No.:        W911NF-10-2-0016, Articles of Collaboration,
                       Article 5, Intellectual Property
  Contractor Name:     General Dynamics Robotic Systems, Inc. (GDRS)
  Contractor Address:  1231 Tech Court, Westminster, MD  21157

  Expiration Date - None

  Technical data and computer software first created by Member(s) in
  performance of the Agreement will be disclosed to the Government.
  General Dynamics Robotic Systems retains the entire right, title, and
  interest throughout the world to each subject invention subject to the
  provisions of this clause and 37 CFR Part 401, 32 CFR 32.36, and
  34 CFR 34.25. The Government shall have the right to obtain, reproduce,
  publish or otherwise use the work for Government purposes.

  NON-EXCLUSIVE LICENSE TO CONSORTIUM PARTICIPANTS
  Consortium Members and subawardees are defined as 'Participants'
  Under Article 5.3, Participants are granted a nonexclusive, royalty-
  free, non-sublicenseable, non-assignable, license to Consortium
  Intellectual Property for the limited purpose of performing tasks under
  The Cooperative Agreement, for Government purposes only, and to make and
  have the same made solely for such use.

*/

#include <math.h> // to allow use of common constants...
#include <common/Error.h>
#include "turtlesim/TeleportRelativeResponse.h"

#include <common/JsonIo.h> // include here so container types are included by the class header 

using namespace std;

const unsigned int turtlesim::TeleportRelativeResponse::ID;
const unsigned int turtlesim::TeleportRelativeResponse::DATA_VERSION;
const std::string turtlesim::TeleportRelativeResponse::DATA_TYPE_NAME = "TeleportRelativeResponse";
const std::string turtlesim::TeleportRelativeResponse::DATA_TYPE_FULL_NAME = "turtlesim::TeleportRelativeResponse";
const std::string turtlesim::TeleportRelativeResponse::VERSION_MD5 = "78196d82ef511cd1ab94e3bfcf24b6e5";
/* xml source for this class */
const std::string turtlesim::TeleportRelativeResponse::XML_SOURCE = "<class name=\"TeleportRelativeResponse\" publicDataMembers=\"true\" sourceIDL=\"ROS\" ros=\"true\" comment=\"\" id=\"1480782637\">\
</class>";

turtlesim::TeleportRelativeResponse::TeleportRelativeResponse() 
{  
};

turtlesim::TeleportRelativeResponse::TeleportRelativeResponse(const turtlesim::TeleportRelativeResponse & inobj) 
{
};

turtlesim::TeleportRelativeResponse::~TeleportRelativeResponse()
{
};

turtlesim::TeleportRelativeResponse * turtlesim::TeleportRelativeResponse::New()
{ 
    return new TeleportRelativeResponse();
};

bool turtlesim::TeleportRelativeResponse::dataTypeFlat() 
{  
    return true;
};

turtlesim::TeleportRelativeResponse & turtlesim::TeleportRelativeResponse::operator=(const turtlesim::TeleportRelativeResponse & inobj)
{
    if (this != &inobj)
    {

        // if datatype is flat, optimize with memcpy (complier level optimiation)
              /*  if (dataTypeFlat() == true)
                  REMOVED invalid when assigning from a parent type as this is the pointer to the derived type, thus turtlesim::TeleportRelativeResponse is copied to the wrong location

        {
            memcpy(this,&inobj,sizeof(turtlesim::TeleportRelativeResponse));
        }
        else */ 
        {

        }
    }

    return *this;
}

bool turtlesim::TeleportRelativeResponse::operator==(const turtlesim::TeleportRelativeResponse & inobj) const
{
    bool ret = true;

    if (this != &inobj)
    { 
    }

    return ret;
}

bool turtlesim::TeleportRelativeResponse::operator!=(const turtlesim::TeleportRelativeResponse & inobj) const
{
    bool ret = false;

    if (this != &inobj)
    {
        ret = !operator==(inobj);
    }

    return ret;
}

bool turtlesim::TeleportRelativeResponse::operator<(const turtlesim::TeleportRelativeResponse & inobj) const
{
    bool ret = false;

    if (this == &inobj)
    {
        ret = false;
    }
    else
    {  
        // comparison algorithm based on std::lexicographical_compare algorithm
        ;
    }

    return ret;
}

bool turtlesim::TeleportRelativeResponse::operator>(const turtlesim::TeleportRelativeResponse & inobj) const
{
    bool ret = false;

    if (this == &inobj)
    {
        ret = false;
    }
    else
    {
        // comparison algorithm based on std::lexicographical_compare algorithm
        ;
    }

    return ret;
}

template <> void rframe::json_io::encode(std::stringstream & sstr, const char * name, const turtlesim::TeleportRelativeResponse & t, std::string & indent, bool lastItem)
{
    if ((name) && (*name != '\0')) rframe::json_io::encodeObjectStart(sstr,name,indent);

    if ((name) && (*name != '\0')) rframe::json_io::encodeObjectEnd(sstr,indent,lastItem);
}

std::string turtlesim::TeleportRelativeResponse::toStr(bool pretty) const
{

    stringstream sstr;
    string indent = (pretty == true) ? "\n" : "";

    rframe::json_io::encodeObjectStartMain(sstr,indent);
    rframe::json_io::encode(sstr,"",*this,indent,true);
    rframe::json_io::encodeObjectEnd(sstr,indent,true); // false so as to  not add , at end of string

    return sstr.str();

};

std::basic_ostream<char>& operator<<(std::basic_ostream<char> &s, const turtlesim::TeleportRelativeResponse & value)
{
    return s << value.toStr(false);
}

